apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  # Định nghĩa một vùng nhớ chia sẻ cho cả hai container.
  # emptyDir là một thư mục tạm thời, sẽ bị xóa khi Pod bị xóa.
  volumes:
    - name: shared-logs
      emptyDir: {}

  # Danh sách các container chạy trong Pod này
  containers:
    # 1. Container chính: Ghi log
    - name: main-container
      image: busybox
      # Lệnh để chạy một vòng lặp, mỗi 2 giây ghi ngày giờ vào file
      command: ["/bin/sh", "-c", "while true; do date >> /var/log/app.log; sleep 2; done"]
      # Gắn vùng nhớ chia sẻ vào container này
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    # 2. Container phụ trợ (Sidecar): Đọc log
    - name: sidecar-container
      image: busybox
      # Lệnh để liên tục đọc file log và in ra standard output
      command: ["/bin/sh", "-c", "tail -f /var/log/app.log"]
      # Gắn CÙNG một vùng nhớ chia sẻ vào container này
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log